# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.BigIntegerField()),
                ('f1', models.FloatField()),
                ('f2', models.FloatField()),
                ('year', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebna.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='frequency',
            name='phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebna.Phrase'),
        ),
        migrations.AddField(
            model_name='frequency',
            name='search_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebna.SearchTerm'),
        ),
        migrations.AddField(
            model_name='frequency',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebna.Source'),
        ),
    ]
