# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parliament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('date_start', models.DateField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('date_end', models.DateField(default=datetime.datetime(1974, 1, 1, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('url', models.URLField()),
                ('img_url', models.URLField()),
                ('occupation', models.TextField()),
                ('birth', models.DateField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpbio.District')),
                ('parliament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpbio.Parliament')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpbio.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpbio.Person')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mpbio.Person'),
        ),
    ]
